apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: itlmc-eventlistner-route
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-itlmc-eventlistner
    weight: 100
