apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: itlmc-eventlistner
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: itlmc-triggerbinding
      template:
        ref: itlmc-triggertemplate
