apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: itlmc-triggerbinding
spec:
  params:
    - name: namespace
      value: itlmc-dev
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)
