apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builder-argo
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - Get
      - List
      - Watch
      - Patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: builder-argo
subjects:
  - kind: ServiceAccount
    name: argocd-operator-controller-manager
    namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: builder-argo